# Generated by Django 3.1.3 on 2020-11-25 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='destianation',
            new_name='destination',
        ),
    ]
